"""
Django settings for projectarsip project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*m*13gg0*3*o_00g5uo4xm8-1a%v^m^+#c&h6ri-%uz@vlr2*z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'rest_framework',
    'arsip.apps.ArsipConfig',
    'model_utils',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projectarsip.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'arsip.views.statistik_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'projectarsip.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Konfigurasi static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # untuk development

# Media files (Jika menggunakan upload file)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # untuk development

X_FRAME_OPTIONS = 'SAMEORIGIN'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],

    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# Login redirect URL
LOGIN_REDIRECT_URL = 'arsip:beranda'
LOGIN_URL = 'arsip:login'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration (SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Ganti dengan SMTP server Anda (misal: smtp.office365.com untuk Outlook)
EMAIL_PORT = 587  # Port untuk TLS
EMAIL_USE_TLS = True  # Gunakan TLS (True untuk port 587)
EMAIL_USE_SSL = False  # Jangan gunakan SSL (gunakan hanya jika port 465)
EMAIL_HOST_USER = '2359201102@umko.ac.id'  # Email pengirim (misal: noreply@arsipdigital.com)
EMAIL_HOST_PASSWORD = 'ofeo lsmw xpjn gsvk '  # Password email atau App Password (untuk Gmail)
DEFAULT_FROM_EMAIL = 'noreply@arsipdigital.com'  # Email default pengirim

# Jazzmin Settings - Konfigurasi Utama
JAZZMIN_SETTINGS = {
    # Tampilan Admin
    "site_title": "Sistem Arsip Digital",
    "site_header": "Arsip Digital",
    "site_brand": "Arsip Digital",
    "site_icon": "fas fa-archive",
    "welcome_sign": "Selamat Datang di Sistem Administrasi Arsip Digital!",

    # URL untuk logo di sidebar (opsional, bisa diganti dengan path gambar Anda)
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo": None,

    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [], # Contoh: ['auth'] untuk menyembunyikan aplikasi Auth & Group
    "hide_models": [],

    # PENTING: Komentari atau Hapus baris "theme" di JAZZMIN_SETTINGS ini
    # agar tema bisa diatur via JAZZMIN_UI_TWEAKS dan live selector.
    # "theme": "darkly", # Ini sekarang diatur di JAZZMIN_UI_TWEAKS

    # Warna Topbar dan Sidebar:
    # Kita buat mereka sangat gelap/hitam agar match dengan tema 'darkly'.
    "topbar_colors": ["navbar-dark", "bg-dark"],
    "sidebar_colors": ["sidebar-dark-primary", "bg-dark"], # sidebar-dark-primary memberikan aksen biru pada item aktif

    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_small_text": False,
    "sidebar_nav_flat_style": False,

    # Fitur UI
    "search_model": ["arsip.Arsip", "auth.User"],
}

# Jazzmin UI Tweaks - Penyesuaian Detail UI
# Pengaturan 'theme' dan 'dark_mode_theme' di sini akan mengaktifkan live theme selector.
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary", # Warna aksen (misalnya link, ikon aktif) akan tetap biru ini

    # Navbar: Kita gunakan setting dari topbar_colors di JAZZMIN_SETTINGS
    "navbar": "navbar-dark bg-dark",

    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_fixed": True,

    # Sidebar: Kita gunakan setting dari sidebar_colors di JAZZMIN_SETTINGS
    "sidebar_chg_h": "accent-primary", # Warna hover di sidebar akan mengikuti aksen
    "sidebar_brand_look": "bg-dark", # Background untuk logo/nama brand di sidebar
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,

    # Tema default untuk Live Theme Selector:
    # Kita set ke 'darkly' untuk tema utama yang konsisten.
    "theme": "darkly",
    "dark_mode_theme": "darkly", # Tema untuk Dark Mode (pastikan sama dengan 'theme' jika ingin konsisten)

    # Kelas CSS untuk tombol (Kita ubah ke yang solid agar lebih menonjol dan sinkron)
    "button_classes": {
        "primary": "btn-primary", # Contoh: Tombol Save akan berwarna solid biru
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}