# Generated by Django 5.2.3 on 2025-07-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsip',
            name='status_akses',
            field=models.CharField(choices=[('publik', 'Publik'), ('internal', 'Internal')], default='internal', max_length=20),
        ),
    ]
